name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        go: ['1.17']
        os: ['ubuntu-18.04', 'macos-10.15']
      fail-fast: false
    name: ${{ matrix.os }} / Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make get-deps

      # Apple Silicon is not supported by Go < 1.16.
      # https://go.dev/blog/go1.16
      - name: Cross-compile all variants
        run: make all-variants
        if: ${{ matrix.go >= '1.16' }}
      - name: Cross-compile all variants except for Apple Silicon
        run: make linux-amd64 linux-arm64 darwin-amd64 windows-amd64 darwin-arm64
        if: ${{ matrix.go < '1.16' }}
      - run: make test
